### ISSUE TITLE
Zombies in level 2 spawn continuously, and old ones sometimes disappear

### ISSUE THREAD

**Issue by emmyF18** [pvcraven/2019_cis390ag#1]
when you stand on the box, they just keep spawning, you can't get past

**Comment by emmyF18** [comment]
When you stand on the box, zombies will come towards you and sometimes disappear. If you move forwards, there will be a large clump of zombies making it hard to beat the game

**Comment by GeoSau** [comment]
Fixed the Spawn rate to make the level actually able to beat it.

**Comment by pvcraven** [comment]
PR #47 integrated. Please test. Close if fixed.

**Comment by KoleHicok** [comment]
Zombie spawners appear to be working much better now. Closing since they appear to work and you can get through the level.
