### ISSUE TITLE
"Video Settings" and "Sound Settings" buttons don't do anything

### ISSUE THREAD

**Issue by bdewerff** [pvcraven/2019_cis390ag#14]
While playing the game, in the "Settings" menu, the "Video Settings" and "Sound Settings" buttons don't work.

Since we can't change any of these settings, we should have a message that shows when they are clicked on that says they are unavailable.

**Comment by bdewerff** [comment]
Fixed this issue by adding in this code for both sound and video settings: 
	public void OpenVideoSettingsMenu(bool isOpen)
	{
		if (isOpen)
		{
			videoSettingsMenu.gameObject.SetActive(true);
			settingsMenu.gameObject.SetActive(false);
		}
		else
		{
			videoSettingsMenu.gameObject.SetActive(false);
			settingsMenu.gameObject.SetActive(true);
		}
	}

Then, I did something similar to how the pause menu switches to the Settings screen when clicking on the "Settings" button.

**Comment by pvcraven** [comment]
Please test, close if fixed.

**Comment by GeoSau** [comment]
They do both show the message that they are currently unavailable.
