### ISSUE TITLE
Player Slides around when they stop moving

### ISSUE THREAD

**Issue by emmyF18** [pvcraven/2019_cis390ag#18]

**Comment by GeoSau** [comment]
after you run and then stop the player will keep sliding making it hard to jump onto or over objects.

**Comment by payton-mcburney** [comment]
Player sliding should either be removed entirely or toned down a bit. In its current state, it feels like the player is moving around on ice, which makes controlling them difficult.

**Comment by J-Luang** [comment]
Fixed this issue by adding a check for rigidbody velocity in Player class under sprint and walk method added code is shown below.
if (rb.velocity.magnitude < .01) 
{
         rb.velocity = Vector3.zero;
}

**Comment by pvcraven** [comment]
Please test and close if fixed.

**Comment by emmyF18** [comment]
Works fine after testing.
