### ISSUE TITLE
Stamina is still used when attacking even if the player has no weapon

### ISSUE THREAD

**Issue by bdewerff** [pvcraven/2019_cis390ag#19]
Pressing the F key decreases stamina no matter if the player is attacking or not.

**Comment by karsonk09** [comment]
### FIXED
Added the following code, which fixed the issue so that the player only uses stamina when pressing the "F" key if they are holding a weapon.
'''if((tory.MeleeWeapon != null || tory.RangedWeapon != null) && Input.GetKeyDown(attack) && tory.Stamina > 10)
        {
            tory.AdjustStamina(-10);
        }'''

**Comment by pvcraven** [comment]
Please test, close if fixed.
