### ISSUE TITLE
Disable the "resume" game button, if there is no game started

### ISSUE THREAD

**Issue by bdewerff** [pvcraven/2019_cis390ag#2]
When the game starts, you can click the "resume" game button even if there is no game saved.

The "resume" game button should be grayed out unless there is a game saved.

**Comment by emmyF18** [comment]
In main menu controller, its shown that the saved game functionality doesn't exist

**Comment by pvcraven** [comment]
Ready for testing

**Comment by J-Luang** [comment]
Works, no resume game button is shown when no game is started.
