### ISSUE TITLE
Jumping should use stamina

### ISSUE THREAD

**Issue by bdewerff** [pvcraven/2019_cis390ag#23]
Currently when jumping, no stamina is used.

When the player jumps, a small amount of stamina should be used. Similar to using the weapon and running.

**Comment by SamuelGabani** [comment]
Can you assign me for this?

**Comment by karsonk09** [comment]
Added the following code to fix the issue:
```
public void Jump()
	{

		// Check and see if we are paused
		if (Time.timeScale == 0)
			return;

		// Check and see if we are on the ground
		Rigidbody2D rb = player.GetComponent<Rigidbody2D>();
		if (this.IsGrounded)
		{
			// Apply force to jump
			Vector2 jumpVelocity = new Vector2(0, jumpForce);
			rb.AddForce(jumpVelocity);
            rb.drag = 1;
            AdjustStamina(-50);
        }
	}
```
I added the "AdjustStamina(-50);" code, which reduces stamina every time the player jumps.

**Comment by SamuelGabani** [comment]
sorry... I didnt see it is assigned already.

**Comment by hmumm** [comment]
I was looking to help with this, but it looks as though it's already complete. Should this be closed? thanks.

**Comment by pvcraven** [comment]
Please test. Close if fixed.

**Comment by karsonk09** [comment]
Testing complete.
