### ISSUE TITLE
Player goes too fast and jumps too high

### ISSUE THREAD

**Issue by payton-mcburney** [pvcraven/2019_cis390ag#25]
When you build the application, the player runs too fast and jumps too high.

**Comment by emmyF18** [comment]
Seems to be based on graphical settings, as very low and low in the settings make the super speed mode, but medium and up work fine.

**Comment by payton-mcburney** [comment]
I fixed the issue with horizontal movement by multiplying the vectors used to apply horizontal force by Time.deltaTime and adjusted the values for walkForce and sprintForce. I also added the parameter ForceMode2D.Impulse to the call to AddForce in the Jump method, which prevented the player from jumping as high. Currently, the player still jumps too high if they are moving while they jump.

**Comment by pvcraven** [comment]
Please test, and close if fixed.

**Comment by GeoSau** [comment]
Just got done testing and the player moves at a good pace and doesn't jump too high.
