### ISSUE TITLE
Audio: Jumping sound plays in the inventory and the pause menu when you press "Space"

### ISSUE THREAD

**Issue by karsonk09** [pvcraven/2019_cis390ag#33]
### Issue:
When you press "Space" in the pause menu or the inventory the sound effect for jumping still plays.
### Expected:
The jumping sound effect should only play when the player initializes a jump and should not only depend on the player pressing the space bar.
### Recommendations:
- Update code so that the sound effect only plays when the player is in contact with the ground and none of the menus are open.

**Comment by pvcraven** [comment]
Please test, close if fixed.

**Comment by GeoSau** [comment]
When I go into to pause menu and the inventory menu and pressed space and there was no jumping sound.
