### ISSUE TITLE
Picking up the gun gives you a knife instead

### ISSUE THREAD

**Issue by emmyF18** [pvcraven/2019_cis390ag#4]
You can't select the gun in the game

**Comment by KoleHicok** [comment]
When the gun it picked up, it looks like it's adding the knife to the inventory instead of the gun.

**Comment by KoleHicok** [comment]
This issue is fixed now. The code was only checking the number of weapons rather than assigning the weapons picked up as use-able. I have called the methods to switch and assign a weapon at the bottom of the player class.

**Comment by pvcraven** [comment]
Please test. Close if fixed.
