### ISSUE TITLE
UI: Stamina bar is based on screen size and becomes too big for its container when the screen is small and too small when the screen is large

### ISSUE THREAD

**Issue by karsonk09** [pvcraven/2019_cis390ag#40]
### Issue:
The stamina bar runs off of the screen when the screen is small. When the screen is large, the stamina bar does not go all the way down.
### Expected:
The stamina bar should go all the way down and hit 0 when there is nothing left in the stamina bar. The stamina bar should not stop before reaching the end of its container.
### Recommendations:
- Update stamina bar code so that it is not based on screen size, but is instead based on the size of its container.

**Comment by J-Luang** [comment]
Fix Health and Status bar bug with resolution, it decreases at the correct rate with the screen that is set when the game launches.
