### ISSUE TITLE
Player: Player can still jump even if stamina is zero.

### ISSUE THREAD

**Issue by karsonk09** [pvcraven/2019_cis390ag#41]
### Issue:
The player can still jump even if their stamina has reached zero, which is not realistic.
### Expected:
Once stamina reaches a certain threshold, the player should not be able to jump until their stamina has replenished enough to jump once more.
### Recommendation:
- Update code so that the jumping action depends on whether or not the player's stamina is above a certain amount.

**Comment by pvcraven** [comment]
Please test. Close if fixed.
