### ISSUE TITLE
You can't run out of stamina

### ISSUE THREAD

**Issue by emmyF18** [pvcraven/2019_cis390ag#7]
### Actual behavior:

You can run forever in the game, and your stamina doesn't run out.

### Expected behavior:

You get tired after running a lot.

### Steps to reproduce/example code:

Just keep jumping and running.

**Comment by bdewerff** [comment]
Fixed this issue with the following code: 
if (sprintKeyDown && walk && tory.Stamina > 2)

I changed the number to 2, which was previously 0, so the stamina would have never run out.

**Comment by J-Luang** [comment]
Tested sprinting & jumping, when stamina reaches zero you can no longer sprint or jump any longer.
