### ISSUE TITLE
Moving up slopes is too difficult

### ISSUE THREAD

**Issue by KoleHicok** [pvcraven/2019_cis390ag#74]
Moving up slopes requires running or else the player moves very slowly up any slope. Even in the tutorial level. The player must either wait or eat food to get to the water. This gets quite frustrating when the player gets stuck moving on the slope and needs to wait for more stamina before they can continue up the slopes.

**Comment by J-Luang** [comment]
Adjusted the value for moving up slope from 1.2f -> 1.8f, decided not to increase speed that much as the player will somewhat move a little slower up slopes, but must be able to do so.
