### ISSUE TITLE
Jumping sound still plays even if the player hits jump while in the air

### ISSUE THREAD

**Issue by bdewerff** [pvcraven/2019_cis390ag#8]
Don't allow sound effects to continuously play. For example, the jumping sound still plays even if the player is in the air.

**Comment by J-Luang** [comment]
Issue before was because it was not checking if the player was grounded in if statement. Added the check as shown below.

if (Input.GetKeyDown(jumpKey) && tory.IsGrounded)

**Comment by KoleHicok** [comment]
I tested this issue and it appears to be working properly.
